<Project>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <PropertyGroup Label="Package Metadata">
    <Version>1.0.0</Version>
    <Authors>Grafirio</Authors>
    <Company>Grafirio</Company>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/Grafirio/Grafirio.Packages</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <PackageReadmeFile Condition="Exists('$(MSBuildProjectDirectory)\README.md')">README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup Condition="Exists('$(MSBuildProjectDirectory)\README.md')">
    <None Include="$(MSBuildProjectDirectory)\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
